INCLUDE(${SGPS_CMAKE_MODULE_PATH}/prettymessage.cmake)

# Macro to add an application that links to ${MRCORE_LIBRARIES}
MACRO(SGPS_ADD_EXECUTABLE PARAM_EXE_NAME PARAM_FILE_LIST)
	SET(EXE_NAME "${PARAM_EXE_NAME}")
	IF("${EXE_NAME}" MATCHES "AUTO")
		STRING(REGEX REPLACE ".*/([^/]*)$" "\\1" EXE_NAME ${CMAKE_CURRENT_SOURCE_DIR})
	ENDIF("${EXE_NAME}" MATCHES "AUTO")
	SET(FILE_LIST ${PARAM_FILE_LIST})
	IF("${FILE_LIST}" STREQUAL "ALL_FILES" OR "${FILE_LIST}" STREQUAL "AUTO")
		FILE(GLOB FILE_LIST "*.cpp" "*.c" "*.cc")
	ENDIF("${FILE_LIST}" STREQUAL "ALL_FILES" OR "${FILE_LIST}" STREQUAL "AUTO")
	IF("${FILE_LIST}" STREQUAL "ALL_FILES_RECURSE")
		FILE(GLOB_RECURSE FILE_LIST "*.cpp" "*.c" "*.cc")
	ENDIF("${FILE_LIST}" STREQUAL "ALL_FILES_RECURSE")

	ADD_EXECUTABLE(${EXE_NAME} ${FILE_LIST})

	INCLUDE_DIRECTORIES("${SGPS_DIR}/src")
	TARGET_LINK_LIBRARIES(${EXE_NAME} sgps)

ENDMACRO(SGPS_ADD_EXECUTABLE)


# Macro to add a MR library in the build system
MACRO(SGPS_ADD_LIBRARY PARAM_FILE_LIST)
	STRING(REGEX REPLACE ".*/([^/]*)$" "\\1" LIBRARY_NAME ${CMAKE_CURRENT_SOURCE_DIR})
	SET(FILE_LIST ${PARAM_FILE_LIST})
	IF("${FILE_LIST}" STREQUAL "ALL_FILES" OR "${FILE_LIST}" STREQUAL "AUTO")
		FILE(GLOB FILE_LIST "*.cpp" "*.c" "*.cc")
	ENDIF("${FILE_LIST}" STREQUAL "ALL_FILES" OR "${FILE_LIST}" STREQUAL "AUTO")
	IF("${FILE_LIST}" STREQUAL "ALL_FILES_RECURSE")
		FILE(GLOB_RECURSE FILE_LIST "*.cpp" "*.c" "*.cc")
	ENDIF("${FILE_LIST}" STREQUAL "ALL_FILES_RECURSE")


	TARGET_LINK_LIBRARIES(${LIBRARY_NAME} sgps)
	INCLUDE_DIRECTORIES("${SGPS_DIR}/src")
	
ENDMACRO(SGPS_ADD_LIBRARY)
