function [ prob ] = gauss_prob( test_pos, init_pos, mu, vvar )
    prob = exp( ...
                -( ...
                    ((test_pos(1)-init_pos(1)) - mu(1)).^2/(2*vvar(1)) + ...
                    ((test_pos(2)-init_pos(2)) - mu(2)).^2/(2*vvar(2))...
                    )...
               );
end


